# shellcheck disable=SC2148

# shellcheck disable=SC1090
[ -n "$PS1" ] \
    && . ~/.zsh_profile

# at the end to make sure it'll overwrite the reverse backsearch
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
